DO $$
BEGIN
    CREATE TYPE quote_category AS ENUM ('inspirational', 'motivational', 'wisdom', 'humor');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Add an enum value with:
-- ALTER TYPE quote_category ADD VALUE 'philosophy';
-- Run this separately from transactions that need to use the new value.
-- PostgreSQL cannot directly remove an enum value. First migrate rows using
-- that value, then recreate the type and convert the column:
-- UPDATE quotes SET category = 'wisdom' WHERE category = 'humor';
-- ALTER TABLE quotes ALTER COLUMN category TYPE text USING category::text;
-- DROP TYPE quote_category;
-- CREATE TYPE quote_category AS ENUM ('inspirational', 'motivational', 'wisdom');
-- ALTER TABLE quotes ALTER COLUMN category TYPE quote_category USING category::quote_category;

CREATE TABLE IF NOT EXISTS author (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quotes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INT NOT NULL REFERENCES author(id),
    text VARCHAR(255) NOT NULL,
    category quote_category NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

WITH inserted_author AS (
    INSERT INTO author (name)
    SELECT 'Oscar Wilde'
    WHERE NOT EXISTS (SELECT 1 FROM author WHERE name = 'Oscar Wilde')
    RETURNING id
), sample_author AS (
    SELECT id FROM author WHERE name = 'Oscar Wilde'
    UNION ALL
    SELECT id FROM inserted_author
    LIMIT 1
), sample_quotes (text, category) AS (
    VALUES
        ('Life is much too important a thing ever to talk seriously about it.', 'humor'),
        ('Experience is the name men give to their mistakes.', 'wisdom'),
        ('Indifference is the revenge the world takes on mediocrities.', 'wisdom'),
        ('When a man has no enemy left there must be something mean about him.', 'wisdom'),
        ('Life imitates art far more than art imitates Life.', 'wisdom'),
        ('No great artist ever sees things as they really are. If he did, he would cease to be an artist.', 'wisdom'),
        ('The final revelation is that Lying, the telling of beautiful untrue things, is the proper aim of Art.', 'wisdom'),
        ('Anybody can make history. Only a great man can write it.', 'wisdom'),
        ('Every great man nowadays has his disciples, and it is always Judas who writes the biography.', 'humor'),
        ('Truth, in the matters of religion, is simply the opinion that has survived.', 'wisdom'),
        ('Oh! journalism is unreadable, and literature is not read.', 'humor'),
        ('The one duty we owe to history is to rewrite it.', 'wisdom'),
        ('Action is the last resource of those who know not how to dream.', 'wisdom'),
        ('There is no sin except stupidity.', 'wisdom'),
        ('Ah! Don''t say you agree with me. When people agree with me I always feel I must be wrong.', 'humor'),
        ('A dreamer is one who can only find his way by moonlight, and his punishment is that he sees the dawn before the rest of the world.', 'inspirational'),
        ('One is tempted to define man as a rational animal who always loses his temper when he is called upon to act in accordance with the dictates of reason.', 'humor'),
        ('A man who does not think for himself does not think at all.', 'wisdom'),
        ('Disobedience, in the eyes of any one who has read history, is man''s original virtue.', 'wisdom'),
        ('A map of the world that does not include Utopia is not worth even glancing at.', 'inspirational'),
        ('The things people say of a man do not alter a man. He is what he is.', 'wisdom'),
        ('All authority is quite degrading.', 'wisdom'),
        ('Selfishness is not living as one wishes to live, it is asking others to live as one wishes to live.', 'wisdom'),
        ('It is absurd to divide people into good and bad. People are either charming or tedious.', 'humor'),
        ('I can resist everything except temptation.', 'humor'),
        ('I am the only person in the world I should like to know thoroughly.', 'wisdom'),
        ('My experience is that as soon as people are old enough to know better, they don''t know anything at all.', 'humor'),
        ('Between men and women there is no friendship possible. There is passion, enmity, worship, love, but no friendship.', 'wisdom'),
        ('My own business always bores me to death. I prefer other people''s.', 'humor'),
        ('Gossip is charming! History is merely gossip. But scandal is gossip made tedious by morality.', 'humor'),
        ('We are all in the gutter, but some of us are looking at the stars.', 'inspirational'),
        ('In this world there are only two tragedies. One is not getting what one wants, and the other is getting it.', 'wisdom'),
        ('A man who knows the price of everything and the value of nothing.', 'wisdom'),
        ('What a pity that in life we only get our lessons when they are of no use to us.', 'wisdom'),
        ('The growing influence of women is the one reassuring thing in our political life.', 'inspirational'),
        ('The youth of America is their oldest tradition. It has been going on now for three hundred years.', 'humor'),
        ('The English country gentleman galloping after a fox - the unspeakable in full pursuit of the uneatable.', 'humor'),
        ('Discontent is the first step in the progress of a man or a nation.', 'motivational'),
        ('To be in society is merely a bore. But to be out of it simply a tragedy.', 'humor'),
        ('Men marry because they are tired; women because they are curious. Both are disappointed.', 'humor'),
        ('I am always astonishing myself. It is the only thing that makes life worth living.', 'inspirational'),
        ('Moderation is a fatal thing. Nothing succeeds like excess.', 'humor'),
        ('The only difference between the saint and the sinner is that every saint has a past and every sinner has a future.', 'wisdom'),
        ('Nothing that is worth knowing can be taught.', 'wisdom'),
        ('The English are always degrading truths into facts. When a truth becomes a fact it loses all its intellectual value.', 'wisdom'),
        ('It is a very sad thing that nowadays there is so little useless information.', 'humor'),
        ('Friendship is far more tragic than love. It lasts longer.', 'wisdom'),
        ('Art is the only serious thing in the world. And the artist is the only person who is never serious.', 'humor'),
        ('The only thing that can console one for being poor is extravagance. The only thing that can console one for being rich is economy.', 'humor'),
        ('One can survive everything nowadays except death.', 'humor'),
        ('Ambition is the last refuge of the failure.', 'wisdom'),
        ('Religions die when they are proved to be true. Science is the record of dead religions.', 'wisdom'),
        ('If one tells the truth, one is sure, sooner or later, to be found out.', 'humor'),
        ('Patriotism is the vice of nations.', 'wisdom'),
        ('Only the shallow know themselves.', 'wisdom'),
        ('In examinations the foolish ask questions that the wise cannot answer.', 'humor'),
        ('The old believe everything; the middle-aged suspect everything; the young know everything.', 'humor'),
        ('To love oneself is the beginning of a lifelong romance.', 'inspirational'),
        ('One should always be a little improbable.', 'inspirational'),
        ('Time is a waste of money.', 'humor'),
        ('The only way to atone for being occasionally a little over-dressed is by being always absolutely over-educated.', 'humor'),
        ('The truth is rarely pure and never simple.', 'wisdom'),
        ('To lose one parent may be regarded as a misfortune; to lose both seems like carelessness.', 'humor'),
        ('An engagement should come on a young girl as a surprise, pleasant or unpleasant as the case may be.', 'humor'),
        ('All women become like their mothers. That is their tragedy. No man does. That is his.', 'humor'),
        ('Of course the music is a great difficulty. You see, if one plays good music, people don''t listen, and if one plays bad music people don''t talk.', 'humor'),
        ('More than half of modern culture depends on what one shouldn''t read.', 'humor'),
        ('Relations are simply a tedious pack of people, who haven''t got the remotest knowledge of how to live, nor the smallest instinct about when to die.', 'humor'),
        ('Memory is the diary that we all carry about with us.', 'wisdom'),
        ('No gentleman ever has any money.', 'humor'),
        ('I never travel without my diary. One should always have something sensational to read in the train.', 'humor'),
        ('The good ended happily, and the bad unhappily. That is what Fiction means.', 'humor'),
        ('I can''t eat muffins in an agitated manner. The butter would probably get on my cuffs.', 'humor'),
        ('Never speak disrespectfully of Society. Only people who can''t get into it do that.', 'humor'),
        ('Thirty-five is a very attractive age. London society is full of women of the very highest birth who have, of their own free choice, remained thirty-five for years.', 'humor'),
        ('I have now realized the vital Importance of Being Earnest.', 'wisdom'),
        ('This suspense is terrible. I hope it will last.', 'humor'),
        ('Only dull people are brilliant at breakfast.', 'humor'),
        ('I always pass on good advice. It is the only thing to do with it. It is never of any use to oneself.', 'humor'),
        ('Women have a wonderful instinct about things. They can discover everything except the obvious.', 'humor'),
        ('Life is never fair. And perhaps it is a good thing for most of us that it is not.', 'wisdom'),
        ('Fashion is what one wears oneself. What is unfashionable is what other people wear.', 'humor'),
        ('The only possible society is oneself.', 'wisdom'),
        ('It is always nice to be expected, and not to arrive.', 'humor'),
        ('Oh, why will parents always appear at the wrong time? Some extraordinary mistake in nature, I suppose.', 'humor'),
        ('When one pays a visit it is for the purpose of wasting other people''s time, not one''s own.', 'humor'),
        ('I don''t like knowing what people say of me behind my back. It makes me far too conceited.', 'humor'),
        ('All charming people, I fancy, are spoiled. It is the secret of their attraction.', 'wisdom'),
        ('A thing is not necessarily true because a man dies for it.', 'wisdom'),
        ('Consistency is the last refuge of the unimaginative.', 'wisdom'),
        ('A poet can survive everything but a misprint.', 'humor'),
        ('A simile committing suicide is always a depressing spectacle.', 'humor'),
        ('We have really everything in common with America nowadays, except, of course, language.', 'humor'),
        ('It is always a silly thing to give advice, but to give good advice is absolutely fatal.', 'humor'),
        ('All art is immoral.', 'wisdom'),
        ('Most people are other people. Their thoughts are someone else''s opinions, their lives a mimicry, their passions a quotation.', 'wisdom'),
        ('Only good questions deserve good answers.', 'wisdom'),
        ('The supreme vice is shallowness.', 'wisdom'),
        ('Where there is sorrow there is holy ground.', 'wisdom'),
        ('A thing is, according to the mode in which one looks at it.', 'wisdom'),
        ('The fact is, that the public have an insatiable curiosity to know everything, except what is worth knowing.', 'wisdom'),
        ('In old days men had the rack. Now they have the press.', 'humor'),
        ('The only thing that one really knows about human nature is that it changes. Change is the one quality we can predicate of it.', 'wisdom')
)
INSERT INTO quotes (author_id, text, category)
SELECT sample_author.id, sample_quotes.text, sample_quotes.category::quote_category
FROM sample_author
CROSS JOIN sample_quotes
WHERE NOT EXISTS (
    SELECT 1
    FROM quotes existing_quote
    WHERE existing_quote.author_id = sample_author.id
      AND existing_quote.text = sample_quotes.text
);
